import ConferenceRoom from '../db/models/conference-room.js';
import logger from '../utils/logger.js';
import asteriskConfigService from './asterisk-config-service.js';

class ConferenceService {
  async createRoom(data) {
    const existing = await ConferenceRoom.findOne({ where: { number: data.number } });
    if (existing) throw new Error(`Conference room number ${data.number} already exists`);
    const room = await ConferenceRoom.create(data);
    logger.info(`✅ Conference Room created: ${room.name} (${room.number})`);
    asteriskConfigService.syncAll().catch(e => logger.warn('Asterisk sync failed:', e.message));
    return room;
  }

  async updateRoom(id, data) {
    const room = await ConferenceRoom.findByPk(id);
    if (!room) throw new Error(`Conference room not found: ${id}`);
    await room.update(data);
    asteriskConfigService.syncAll().catch(e => logger.warn('Asterisk sync failed:', e.message));
    return room;
  }

  async deleteRoom(id) {
    const room = await ConferenceRoom.findByPk(id);
    if (!room) throw new Error(`Conference room not found: ${id}`);
    await room.destroy();
    asteriskConfigService.syncAll().catch(e => logger.warn('Asterisk sync failed:', e.message));
    return room;
  }

  async getRooms(limit = 100, offset = 0) {
    return ConferenceRoom.findAndCountAll({ limit, offset, order: [['number', 'ASC']] });
  }

  async getRoomDetail(id) {
    const room = await ConferenceRoom.findByPk(id);
    if (!room) throw new Error(`Conference room not found: ${id}`);
    return room;
  }

  // Generate confbridge.conf content
  generateConfbridgeConf(rooms) {
    const lines = [];
    lines.push('; ConfBridge configuration - generated by Telro');
    lines.push('');
    lines.push('[general]');
    lines.push('');
    // Default user profile
    lines.push('[default_user]');
    lines.push('type = user');
    lines.push('music_on_hold_when_empty = yes');
    lines.push('quiet = no');
    lines.push('announce_user_count = yes');
    lines.push('');
    // Default bridge profile
    lines.push('[default_bridge]');
    lines.push('type = bridge');
    lines.push('max_members = 50');
    lines.push('');
    for (const room of rooms) {
      if (!room.enabled) continue;
      lines.push(`[room-${room.number}]`);
      lines.push(`type = bridge`);
      lines.push(`max_members = ${room.maxMembers}`);
      if (room.recordEnabled) lines.push(`record_conference = yes`);
      if (room.musicOnHold) lines.push(`music_on_hold_when_empty = yes`);
      if (room.waitForHost) lines.push(`wait_for_leader = yes`);
      lines.push('');
    }
    return lines.join('\n');
  }
}

export default new ConferenceService();
